### ISSUE TITLE
Issue after plugin after plugin upgrade

### ISSUE THREAD

**Issue by gabriellezbautista** [Nerdwin15/stash-jenkins-postreceive-webhook#141]
error when the build is triggered due to an SCM change. It works fine when triggered manually:
stderr: fatal: ambiguous argument '50c3d4609e8bb53471acc95fd0587520f57c85bf^
{commit}
': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] – [<file>...]'
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1567)
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1563)
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1249)
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1261)
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:622)
at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:85)
at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:903)
at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1017)
at hudson.scm.SCM.checkout(SCM.java:485)
at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:118)
at hudson.model.AbstractProject.checkout(AbstractProject.java:1282)
at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
at hudson.model.Run.execute(Run.java:1741)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:381)

Note: We already did the workaround in https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/issues/91

**Comment by thrownullpointer** [comment]
What version of stash or bitbucket? What jenkins version?
