### ISSUE TITLE
Issue with connecting jenkins

### ISSUE THREAD

**Issue by cmg1986** [Nerdwin15/stash-jenkins-postreceive-webhook#195]
Hello,
In the SETUP steps mentioned at https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook like "If using HTTP, enter the username that Jenkins is using to clone your repository" but unable to find where do i need to mentioned Username as its picks repo url itself.
![capture](https://user-images.githubusercontent.com/19831124/28364259-490ea610-6ca1-11e7-8c31-3d94028836b5.JPG)

Also when i am trying to "trigger jenkins" getting exception for server unreachable every time.

java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_65]
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:532) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.1.jar:4.5.1]

**Comment by rtrompier** [comment]
+1

**Comment by alexBraidwood** [comment]
@cmg1986 What version of Bitbucket are you running? If you're on 5.0+, it may help to build a new jar  from this pull request: #191
