### ISSUE TITLE
Team Foundation Server Plug-in (Jenkins + TFS)

### ISSUE THREAD

**Issue by Leo-gred** [Nerdwin15/stash-jenkins-postreceive-webhook#212]
Hi, everyone.
I have configured Jenkins + TFS using "Team Foundation Server Plug-in". According to trigger, when i make commit plugin starts job on Jenkins. But in logs i can see next `error:
```
Started by user admin
ERROR: Error while trying to update pending status in TFS/Team Services
java.lang.NullPointerException
	at hudson.plugins.tfs.util.UriHelper.join(UriHelper.java:229)
	at hudson.plugins.tfs.util.UriHelper.join(UriHelper.java:196)
	at hudson.plugins.tfs.util.TeamRestClient.addCommitStatus(TeamRestClient.java:223)
	at hudson.plugins.tfs.util.TeamStatus.createFromRun(TeamStatus.java:74)
	at hudson.plugins.tfs.TeamPendingStatusBuildStep.perform(TeamPendingStatusBuildStep.java:44)
	at hudson.plugins.tfs.TeamGlobalStatusPoster.onStarted(TeamGlobalStatusPoster.java:20)
	at hudson.plugins.tfs.TeamGlobalStatusPoster.onStarted(TeamGlobalStatusPoster.java:13)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1811)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[EnvInject] - Loading node environment variables.
Building in workspace C:\buildDir\services\GSEC_TEST
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
********************************************************* part of repository*********************************************************

 > git.exe rev-parse "null^{commit}" # timeout=10
FATAL: Command "git.exe rev-parse "null^{commit}"" returned status code 128:
stdout: null^{commit}

stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git.exe rev-parse "null^{commit}"" returned status code 128:
stdout: null^{commit}

stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1966)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1597)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1609)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:794)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1070)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1187)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Error while trying to update completion status in TFS/Team Services
```

Please help with this problem. is it a problem with configuration or with plugin?

**Comment by kimx** [comment]
You need to modify "Integration level".
![integration level](https://user-images.githubusercontent.com/5724118/50075969-54b48500-021b-11e9-850c-f184190fabf1.png)
